# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hauptfenster.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 1241, 731))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLabortagebuch = QtWidgets.QPushButton(self.widget)
        self.btnLabortagebuch.setObjectName("btnLabortagebuch")
        self.horizontalLayout.addWidget(self.btnLabortagebuch)
        self.btnErgebnisse = QtWidgets.QPushButton(self.widget)
        self.btnErgebnisse.setObjectName("btnErgebnisse")
        self.horizontalLayout.addWidget(self.btnErgebnisse)
        self.btnErgebnisse_2 = QtWidgets.QPushButton(self.widget)
        self.btnErgebnisse_2.setObjectName("btnErgebnisse_2")
        self.horizontalLayout.addWidget(self.btnErgebnisse_2)
        self.btnStammdaten = QtWidgets.QPushButton(self.widget)
        self.btnStammdaten.setObjectName("btnStammdaten")
        self.horizontalLayout.addWidget(self.btnStammdaten)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.btnAktualisierenProben = QtWidgets.QPushButton(self.widget)
        self.btnAktualisierenProben.setObjectName("btnAktualisierenProben")
        self.verticalLayout.addWidget(self.btnAktualisierenProben)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.listWidget_3 = QtWidgets.QListWidget(self.widget)
        self.listWidget_3.setObjectName("listWidget_3")
        self.horizontalLayout_2.addWidget(self.listWidget_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.widget)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_2.addWidget(self.calendarWidget)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.listWidget_2 = QtWidgets.QListWidget(self.widget)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_2.addWidget(self.listWidget_2)
        self.btnNeuerTermin = QtWidgets.QPushButton(self.widget)
        self.btnNeuerTermin.setObjectName("btnNeuerTermin")
        self.verticalLayout_2.addWidget(self.btnNeuerTermin)
        self.btnAktualisierenTermine = QtWidgets.QPushButton(self.widget)
        self.btnAktualisierenTermine.setObjectName("btnAktualisierenTermine")
        self.verticalLayout_2.addWidget(self.btnAktualisierenTermine)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionDebug = QtWidgets.QAction(MainWindow)
        self.actionDebug.setObjectName("actionDebug")
        self.menuFile.addAction(self.actionEdit)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionDebug)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnLabortagebuch.setText(_translate("MainWindow", "Labortagebuch"))
        self.btnErgebnisse.setText(_translate("MainWindow", "Ergebnisse"))
        self.btnErgebnisse_2.setText(_translate("MainWindow", "Ergebnisse"))
        self.btnStammdaten.setText(_translate("MainWindow", "Stammdaten"))
        self.label.setText(_translate("MainWindow", "Proben heute:"))
        self.btnAktualisierenProben.setText(_translate("MainWindow", "Aktualisieren"))
        self.label_2.setText(_translate("MainWindow", "Termine"))
        self.btnNeuerTermin.setText(_translate("MainWindow", "Neuer Termin"))
        self.btnAktualisierenTermine.setText(_translate("MainWindow", "Aktualisieren"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionDebug.setText(_translate("MainWindow", "Debug"))

